package:
    name: std_daq_service
    version: 1.0.0

source:
    path: .

requirements:
  build:
      - python
  run:
      - python
      - pyzmq
      - pyepics
      - flask
      - pika

build:
  number: 0

  entry_points:
    - epics_buffer = std_daq_service.epics_buffer.start:main
    - daq_listener = std_daq_service.listener.start:main
    - rest_proxy = std_daq_service.rest.start:main
    - writer_agent = std_daq_service.writer_agent.start:main

about:
    home: https://github.com/paulscherrerinstitute/std_daq_service